# Generated by Django 5.1.1 on 2024-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("date_posted", models.DateField()),
                ("type", models.CharField(max_length=50)),
                ("job_url", models.CharField(max_length=1000)),
            ],
        ),
    ]
