# Generated by Django 5.1.1 on 2024-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="field",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
