# Generated by Django 5.1.1 on 2024-09-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_job_company_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="date_posted",
            field=models.DateField(blank=True, null=True),
        ),
    ]
